require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'example' do
  use_unimodules!
  config = use_native_modules!
  
  pod 'secp256k1.c', '0.1.2', :modular_headers => true
  use_react_native!(:path => config["reactNativePath"])


    # Enables Flipper.

    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    use_flipper!({ 'Flipper-Folly' => '2.6.9' }) # update this part
    post_install do |installer|
      flipper_post_install(installer)
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
end
