# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

workspace 'RNTorusDirectSDK'
platform :ios, '10.0'

ENV['SWIFT_VERSION'] = '5'

target 'RNTorusDirectSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
    
  pod 'secp256k1.c', '0.1.2', :modular_headers => true
  pod 'Torus-directSDK', '~> 0.3.0'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  # Pods for RNTorusDirectSdk

end
